Ensize = 40; % ensemble size
data = 'Iris'; 
load(data);
X = zscore(fea); % features
Y = gnd; % labels
[N,~] = size(X);
if(min(Y)<=0)
    Y = Y-min(Y)+1;
end % Be sure that labels are positive
realK = length(unique(Y)); % real number of clusters
krange = [realK,realK]; % krange = [2, 2*realK];
cls = getenclus(X,Ensize,krange,2); % each column is one solution;  generated by kmeans
CoMatrix = GetCoassociationMatrix(cls'); 
weight = Getweight2(CoMatrix);
[S_WOSP,S_WOHB,nc] = GetSimMatrices(X, weight, cls); % get similarity matrices for WOSP and WOHB
% WOMC
cl = WOMC(cls',weight,realK);
[ARI,RI,~,~]=valid_RandIndex(Y,cl);
NMI = GetNMI(Y,cl);     
fprintf('The results of WOMC: ARI=%f, RI=%f, NMI=%f\n\n\n',ARI,RI,NMI);

% WOSP
cl = WOSP(S_WOSP,realK);
[ARI,RI,~,~]=valid_RandIndex(Y,cl);
NMI = GetNMI(Y,cl);     
fprintf('The results of WOSP: ARI=%f, RI=%f, NMI=%f\n\n\n',ARI,RI,NMI);

% WOHB_METIS
cl = WOHB_METIS(S_WOHB, realK, nc);
[ARI,RI,~,~]=valid_RandIndex(Y,cl);
NMI = GetNMI(Y,cl);     
fprintf('The results of WOHB: ARI=%f, RI=%f, NMI=%f\n\n\n',ARI,RI,NMI);

% WOKmeans
disp('CLUSTER ENSEMBLES using WOKmeans');
temp = randperm(N);
[IniK,~] = sort(temp(1:realK),'ascend');  
InitC = X(IniK,:);
[cl, ~, ~, ~] = WeightedKmeans(X, realK, InitC, 100, weight);
[ARI,RI,~,~]=valid_RandIndex(Y,cl);
NMI = GetNMI(Y,cl);     
fprintf('The results of WOKmeans: ARI=%f, RI=%f, NMI=%f\n',ARI,RI,NMI);
