clear all
data_set={'COIL100.mat';};
%     ;'Glass_2classes.mat';'Heart.mat';'Ionosphere.mat'...
%     ;'Iris.mat';'Iris-f3&4.mat'...
%     ;'Pima.mat';'Protein.mat';'Protein_3classes.mat'...
%     ;'Sonar.mat';'Soybean-small.mat';'Wine.mat'};
%     'Breast.mat';'Glass.mat'...
%     'Glass_2classes.mat';'Heart.mat';'Ionosphere.mat'...
%     ;'Iris.mat';'Iris-f3&4.mat';'NCI60.mat'...
%     ;'Pima.mat';'Protein.mat';'Protein_3classes.mat'...
%     ;'Sonar.mat';'Soybean-small.mat';'Wine.mat'...
%     ;'Zip.mat';'Zip_2classes.mat'
%     '10digit(No-NaN).mat';'10digit.mat';'10digit_2classes.mat'...
%     ;'20Newsgroups(3classes-nozero).mat';'COIL20.mat';'COIL20_10classes.mat';'20Newsgroups(3classes-origi).mat'...
%     ;'COIL20_2classes.mat';'COIL20_3classes.mat';'COIL20_4classes.mat'...
%     ;'COIL20_5classes.mat';'COIL20_6classes.mat';'COIL20_7classes.mat'...
%     ;'COIL20_8classes.mat';'COIL20_class_2_3.mat'...
%     ;'MNIST_100_100.mat';'MNIST_150_150.mat';'ORL-32x32.mat';'ORL-64x64.mat'...
%     ;'Reuters(3classes)_10.mat';'Reuters(3classes)_12.mat'...
%     ;'Reuters(3classes)_15.mat';'Reuters(3classes)_34.mat';'Reuters(3classes)_45.mat'...
%     'Yale-32x32.mat';'Yale-64x64.mat';'yaleB.mat'...
%     ;'YaleB-32x32.mat';'yaleB-759.mat'};
%     ;'COIL100.mat';'Copy_of_10digit.mat';'Isolet1.mat'...
%     ;'Isolet1-300.mat';'Isolet2.mat';'Isolet3.mat'...
%     ;'Isolet4.mat';'Isolet5.mat';'MNIST_2k2k.mat'...   
%     ;'Pose27-64x64.mat';'PIE-32x32.mat';'PIE-2040.mat'...
%     ;'Reuters21578.mat';'Spam.mat';'Spam_150_150.mat'...
%     ;'TDT2.mat';'USPS.mat';'USPS_3classes.mat'...
%     ;'USPS_150_150.mat';'USPS_150_150_150.mat';'usps-all.mat'...
    
    %     ;'';'';''...
    
mcp=0.05;
ccp=0.05;
sub_database_num=5;

AR=zeros(length(data_set),4);
RI=zeros(length(data_set),4);
MI=zeros(length(data_set),4);
HI=zeros(length(data_set),4);
NMI=zeros(length(data_set),4);
result=zeros(length(data_set),24);

for i=1:length(data_set)
    clearvars -except data_set AR RI MI HI p i mcp ccp sub_database_num
    %remember to change the above parameters
    file_name=data_set{i};
    
    AR_AVE=zeros(10,4);
    RI_AVE=zeros(10,4);
    MI_AVE=zeros(10,4);
    HI_AVE=zeros(10,4);
    NMI_AVE=zeros(10,4);
    
    for j=1:10
        [n(i),m(i),k(i),AR(i,:),RI(i,:),MI(i,:),HI(i,:),NMI(i,:)]=SSEC(file_name,mcp,ccp,sub_database_num);
        AR_AVE(j,:)=AR(i,:);
        RI_AVE(j,:)=RI(i,:);
        MI_AVE(j,:)=MI(i,:);
        HI_AVE(j,:)=HI(i,:);
        NMI_AVE(j,:)=NMI(i,:);
    end
    
    AR(i,:)=mean(AR_AVE);
    RI(i,:)=mean(RI_AVE);
    MI(i,:)=mean(MI_AVE);
    HI(i,:)=mean(HI_AVE);
    NMI(i,:)=mean(NMI_AVE);
    
    fprintf('data_set: %s\n',data_set{i});
    %result(i,:)=[data_set(i),n(i),m(i),k(i),AR(i,:) RI(i,:) MI(i,:) HI(i,:) NMI(i,:)];
    result(i,:)=[data_set(i),n(i),m(i),k(i),AR(i,1),AR(i,2),AR(i,3),AR(i,4),...
        RI(i,1),RI(i,2),RI(i,3),RI(i,4),MI(i,1),MI(i,2),MI(i,3),MI(i,4),...
        HI(i,1),HI(i,2),HI(i,3),HI(i,4),NMI(i,1),NMI(i,2),NMI(i,3),NMI(i,4)];
end
